#Created from stadard compile template of POND
#Current Module:Template
################################################################
DEPENDED_MODULES := 
INCLUDE :=
LIBS := 
CULIBS := -lcurand
SUBDIRS :=
#MPI_ENABLE := True
################################################################
################################################################
CC := pcc
FORCC := gfortran
MPIFORCC := mpifort
################################################################
MAKE := make
################################################################
FLAGS := -std=c++11 -O2 --compiler-options -Wno-unused-function --compiler-options -Wno-sign-compare
DFLAGS := -std=c++11 -g -G -D DEBUG --compiler-options -g  --compiler-options -Wall --compiler-options -Wextra --compiler-options -Wno-unused --compiler-options -Wno-unused-parameter  --compiler-options -fno-inline-functions --compiler-options -Wno-unused-function --compiler-options -Wno-sign-compare
FORFLAGS := -O2
DFORFLAGS := -g -D DEBUG -Wall -Wextra  -Wno-unused -Wno-unused-parameter 
################################################################
ModuleName := $(notdir $(CURDIR))Module
EXCU := exe
OS = $(POND_OS_TYPE)
SHELL := /bin/bash

CUINCLUDE:=$(INCLUDE) `pond-path tcu $(DEPENDED_MODULES)` 
INCLUDE:=$(INCLUDE) `pond-path tcpp $(DEPENDED_MODULES)` 

SRCS := $(wildcard *.cpp)
CSRCS := $(wildcard *.c)
CUSRCS := $(wildcard *.cu)
FORSRCS := $(wildcard *.f90)
HEADERS := $(wildcard *.h) $(POND_ROOT)/pond/include/pond.h

DOBJECTS := $(patsubst %.cpp, build/debug/%.tcpp.o, $(SRCS))
DCOBJECTS := $(patsubst %.c, build/debug/%.tc.o, $(CSRCS))
DCUOBJECTS := $(patsubst %.cu, build/debug/%.tcu.o, $(CUSRCS))
DCUCPPOBJECTS := $(patsubst %.cu, build/debug/%.tcu.o.tcpp.o, $(CUSRCS))
DFOROBJECTS := $(patsubst %.f90, build/debug/%.tf90.o, $(FORSRCS))
DALLCPPOBJECTS := $(DOBJECTS) $(DCOBJECTS) $(DCUCPPOBJECTS) $(DFOROBJECTS)
DALLCUOBJECTS := $(DOBJECTS) $(DCOBJECTS) $(DCUOBJECTS) $(DFOROBJECTS)

OBJECTS := $(patsubst %.cpp, build/release/%.tcpp.o, $(SRCS))
COBJECTS := $(patsubst %.c, build/release/%.tc.o, $(CSRCS))
CUOBJECTS := $(patsubst %.cu, build/release/%.tcu.o, $(CUSRCS))
CUCPPOBJECTS := $(patsubst %.cu, build/release/%.tcu.o.tcpp.o, $(CUSRCS))
FOROBJECTS := $(patsubst %.f90, build/release/%.tf90.o, $(FORSRCS))
ALLCPPOBJECTS := $(OBJECTS) $(COBJECTS) $(CUCPPOBJECTS) $(FOROBJECTS)
ALLCUOBJECTS := $(OBJECTS) $(COBJECTS) $(CUOBJECTS) $(FOROBJECTS)

DCUDAVERSION := 
CUDAVERSION := 
ifdef CUOBJECTS
	DCUDAVERSION := DCUALL
	CUDAVERSION := CUALL
endif

ifeq ($(MPI_ENABLE),True)
	LIBS := $(LIBS) -lmpi
	FORCC := $(MPIFORCC)
endif

OSFIX :=
ifeq ($(OS),GNU/Linux)
	FLAGS := $(FLAGS) -DOS_LINUX
	DFLAGS := $(DFLAGS) -DOS_LINUX
endif
ifeq ($(OS),Cygwin)
	OSFIX :=WIN
	FLAGS := $(FLAGS) -DOS_WINDOWS -U__STRICT_ANSI__
	DFLAGS := $(DFLAGS) -DOS_WINDOWS -U__STRICT_ANSI__
	DCUDAVERSION := 
	CUDAVERSION := 
endif

#################################################################
################################################################
normal: debug

all: debug release

install: $(RELEASE) upload

debug: all-prepare DCPPALL$(OSFIX) $(DCUDAVERSION) post-work

release: all-prepare CPPALL$(OSFIX) $(CUDAVERSION) post-work

########################################################################################################
DCUALL: $(DALLCUOBJECTS)
	$(CC) $(DFLAGS) -shared -o lib$(ModuleName)_cuda-dev.so $(DALLCUOBJECTS) $(CUINCLUDE)  $(LIBS) $(CULIBS)
	$(CC) $(DFLAGS) -o $(EXCU) $(DALLCUOBJECTS) $(CUINCLUDE) $(LIBS) -lpd
DCPPALL: $(DALLCPPOBJECTS)
	$(CC) $(DFLAGS) -fc++ -shared -o lib$(ModuleName)-dev.so $(DALLCPPOBJECTS) $(INCLUDE)  $(LIBS) 
	$(CC) $(DFLAGS) -fc++ -o $(EXCU) $(DALLCPPOBJECTS) $(INCLUDE) $(LIBS) -lpd
DCPPALLWIN: $(DALLCPPOBJECTS)
	$(CC) $(FLAGS) -fc++ -shared -o lib$(ModuleName).dll $(DALLCPPOBJECTS) $(INCLUDE)  $(LIBS) -lpd
	$(CC) $(DFLAGS) -fc++ -o $(EXCU) $(DALLCPPOBJECTS) $(INCLUDE) $(LIBS) -lpd
build/debug/%.tcu.o: %.cu $(HEADERS)
	$(CC) $(DFLAGS) -Xcompiler -fPIC -c $< -o $@ -I. $(CUINCLUDE)
build/debug/%.tcu.o.tcpp.o: %.cu $(HEADERS)
	$(CC) $(DFLAGS) -fc++ -Xcompiler -fPIC -c $< -o $@ -I. $(INCLUDE)
build/debug/%.tcpp.o: %.cpp $(HEADERS)
	$(CC) $(DFLAGS) -Xcompiler -fPIC -c $< -o $@ -I. $(INCLUDE)
build/debug/%.tc.o: %.c $(HEADERS)
	$(CC) $(DFLAGS) -Xcompiler -fPIC -c $< -o $@ -I. $(INCLUDE)
build/debug/%.tf90.o: %.f90 $(HEADERS)
	$(FORCC) $(DFORFLAGS) -fPIC -c $< -o $@ -I. $(INCLUDE)

#########################################################################################################
CUALL: $(ALLCUOBJECTS)
	$(CC) $(FLAGS) -shared -o lib$(ModuleName)_cuda.so $(ALLCUOBJECTS) $(CUINCLUDE)  $(LIBS) $(CULIBS)
	$(shell if [ ! -d $(HOME_POND)/.temp ]; then mkdir $(HOME_POND)/.temp; fi; rmcp  lib$(ModuleName)_cuda.so $(HOME_POND)/.temp/  )
CPPALL: $(ALLCPPOBJECTS)
	$(CC) $(FLAGS) -fc++ -shared -o lib$(ModuleName).so $(ALLCPPOBJECTS) $(INCLUDE)  $(LIBS) 
	$(shell if [ ! -d $(HOME_POND)/.temp ]; then mkdir $(HOME_POND)/.temp; fi; rmcp  lib$(ModuleName).so $(HOME_POND)/.temp/  )
CPPALLWIN: $(ALLCPPOBJECTS)
	$(CC) $(FLAGS) -fc++ -shared -o lib$(ModuleName).dll $(ALLCPPOBJECTS) $(INCLUDE)  $(LIBS)  -lpd
	$(shell if [ ! -d $(HOME_POND)/.temp ]; then mkdir $(HOME_POND)/.temp; fi; rmcp  lib$(ModuleName).dll $(HOME_POND)/.temp/  )
build/release/%.tcu.o: %.cu $(HEADERS)
	$(CC) $(FLAGS) -Xcompiler -fPIC -c $< -o $@ -I. $(CUINCLUDE)
build/release/%.tcpp.o: %.cpp $(HEADERS)
	$(CC) $(FLAGS) -Xcompiler -fPIC -c $< -o $@ -I. $(INCLUDE)
build/release/%.tc.o: %.c $(HEADERS)
	$(CC) $(FLAGS) -Xcompiler -fPIC -c $< -o $@ -I. $(INCLUDE)
build/release/%.tf90.o: %.f90 $(HEADERS)
	$(FORCC) $(FORFLAGS) -fPIC -c $< -o $@ -I. $(INCLUDE)

#########################################################################################################
clean:
	@echo "clean up *.o, *.so, *.dll, exe ..."
	@rm -rf build/*;
	@if [ -f exe ]; then rm exe; fi
	@if [ -f lib$(ModuleName).so ]; then rm lib$(ModuleName).so; fi
	@if [ -f lib$(ModuleName)-dev.so ]; then rm lib$(ModuleName)-dev.so; fi
	@if [ -f lib$(ModuleName).dll ]; then rm lib$(ModuleName).dll; fi

#####################################################################################

all-prepare: 
	@echo "current os is " $(OS)
	@if [ "x`pond-path pcc $(DEPENDED_MODULES)`" == "x" ]; \
		then echo "Error: Dependency failed.";\
		exit 2;\
		else echo "$(DEPENDED_MODULES)">.requirement;\
		fi 
	$(shell if [ -f build ]; then rm build; mkdir build; elif ! [ -d build ]; then mkdir build; fi; )
	$(shell if [ -f build/debug ]; then rm build/debug; mkdir build/debug; elif ! [ -d build/debug ]; then mkdir build/debug; fi; )
	$(shell if [ -f build/release ]; then rm build/release; mkdir build/release; elif ! [ -d build/release ]; then mkdir build/release; fi; )
	@rmcp *.h ../../include/
post-work:
	@rmcp *.so ../../lib/
	@rmcp *.dll ../../lib/

upload:
	@echo "Upload to POND server"
	$(shell pond upload)
